# Header
menu:
  "Charlie ⌂": /topHome
  "Home": /
  "Percent Correct": /percentCorrect
  "Players": /players
  "Number of Games": /numberOfGames
  "Final Jeopardy": /finalJeopardy
  "Seasons": /seasonsAndYears
  "About": /about

# Content
rss: /atom.xml
excerpt_link: Read More
fancybox: true
#favicon: favicon.ico
#subtitle:

# Sidebar, can be 'bottom', 'right', 'left', or false
sidebar: bottom
# we could add new widget types into layout/_partual/_widget directory
widgets:
- recent_posts
- archive
- tagcloud
- tag
- category
index_widgets:

# Miscellaneous
google_analytics: UA-7726174-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
